Fixed file reference, still have problems with forward reference...
It appears that there's a problem loading files with jshell's "/open"
command when they depend on one another.

  @src/experiments/java$ jshell
  |  Welcome to JShell -- Version 9
  |  For an introduction type: /help intro

  jshell> /open ZoomPanLib.java

  jshell> /open XML_Parser.java

  jshell> /open Reconstruct.java

  jshell> /types
  |    class ZoomPanLib
  |    class XML_Parser
  |    class MyFileChooser
  |    class Reconstruct
  |       which cannot be referenced until class SeriesClass is declared

  jshell> /open SeriesClass.java

  jshell> /types
  |    class ZoomPanLib
  |    class XML_Parser
  |    class MyFileChooser
  |    class Reconstruct
  |       which cannot be referenced until class SeriesClass is declared
  |    class SeriesClass
  |       which cannot be referenced until class SectionClass is declared

  jshell> /open SectionClass.java
  |  Error:
  |  cannot find symbol
  |    symbol:   class Reconstruct
  |    public void draw_stroke ( Graphics g, ArrayList<double[]> s, Reconstruct r ) {
  |                                                                 ^---------^
  |  Error:
  |  cannot find symbol
  |    symbol:   class Reconstruct
  |   public void paint_section (Graphics g, Reconstruct r, SeriesClass series) {
  |                                          ^---------^
  |  Error:
  |  cannot find symbol
  |    symbol:   class SeriesClass
  |   public void paint_section (Graphics g, Reconstruct r, SeriesClass series) {
  |                                                         ^---------^
  |  Error:
  |  illegal start of type
  |      if (r.center_draw) {
  |         ^-------------^

  jshell>